name: flottiecook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.17
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/ 
  - assets/icon/
  - assets/images/

  
